CREATE TABLE RECS_2015 (
  DOEID integer,
  REGIONC integer,
  DIVISION integer,
  METROMICRO text,
  UATYP10 text,
  CDD30YR integer,
  CDD65 integer,
  CLIMATE_REGION_PUB text,
  HDD30YR integer,
  HDD65 integer,
  TYPEHUQ integer,
  ZTYPEHUQ integer,
  CELLAR integer,
  ZCELLAR integer,
  BASEFIN integer,
  ZBASEFIN integer,
  ATTIC integer,
  ZATTIC integer,
  ATTICFIN integer,
  ZATTICFIN integer,
  STORIES integer,
  ZSTORIES integer,
  PRKGPLC1 integer,
  ZPRKGPLC1 integer,
  SIZEOFGARAGE integer,
  ZSIZEOFGARAGE integer,
  KOWNRENT integer,
  ZKOWNRENT integer,
  YEARMADERANGE integer,
  ZYEARMADERANGE integer,
  OCCUPYYRANGE integer,
  ZOCCUPYYRANGE integer,
  STUDIO integer,
  ZSTUDIO integer,
  BEDROOMS integer,
  ZBEDROOMS integer,
  NCOMBATH integer,
  ZNCOMBATH integer,
  NHAFBATH integer,
  ZNHAFBATH integer,
  OTHROOMS integer,
  ZOTHROOMS integer,
  TOTROOMS integer,
  ZTOTROOMS integer,
  WALLTYPE integer,
  ZWALLTYPE integer,
  ROOFTYPE integer,
  ZROOFTYPE integer,
  HIGHCEIL integer,
  ZHIGHCEIL integer,
  DOOR1SUM integer,
  ZDOOR1SUM integer,
  WINDOWS integer,
  ZWINDOWS integer,
  TYPEGLASS integer,
  ZTYPEGLASS integer,
  WINFRAME integer,
  ZWINFRAME integer,
  ADQINSUL integer,
  ZADQINSUL integer,
  DRAFTY integer,
  ZDRAFTY integer,
  UGASHERE integer,
  ZUGASHERE integer,
  SWIMPOOL integer,
  ZSWIMPOOL integer,
  MONPOOL integer,
  ZMONPOOL integer,
  POOL integer,
  ZPOOL integer,
  FUELPOOL integer,
  ZFUELPOOL integer,
  RECBATH integer,
  ZRECBATH integer,
  MONTUB integer,
  ZMONTUB integer,
  FUELTUB integer,
  ZFUELTUB integer,
  OUTLET integer,
  ZOUTLET integer,
  ALTFUELPEV integer,
  ZALTFUELPEV integer,
  BACKUP integer,
  ZBACKUP integer,
  SOLAR integer,
  NUMFRIG integer,
  ZNUMFRIG integer,
  SIZRFRI1 integer,
  ZSIZRFRI1 integer,
  TYPERFR1 integer,
  ZTYPERFR1 integer,
  AGERFRI1 integer,
  ZAGERFRI1 integer,
  ICE integer,
  ZICE integer,
  SIZRFRI2 integer,
  ZSIZRFRI2 integer,
  TYPERFR2 integer,
  ZTYPERFR2 integer,
  AGERFRI2 integer,
  ZAGERFRI2 integer,
  LOCRFRI2 integer,
  ZLOCRFRI2 integer,
  NUMFREEZ integer,
  ZNUMFREEZ integer,
  UPRTFRZR integer,
  ZUPRTFRZR integer,
  SIZFREEZ integer,
  ZSIZFREEZ integer,
  AGEFRZR integer,
  ZAGEFRZR integer,
  STOVEN integer,
  ZSTOVEN integer,
  STOVENFUEL integer,
  ZSTOVENFUEL integer,
  DUALCOOKTFUEL integer,
  ZDUALCOOKTFUEL integer,
  DUALOVENFUEL integer,
  ZDUALOVENFUEL integer,
  COOKTUSE integer,
  ZCOOKTUSE integer,
  OVENUSE integer,
  ZOVENUSE integer,
  STOVE integer,
  ZSTOVE integer,
  STOVEFUEL integer,
  ZSTOVEFUEL integer,
  SEPCOOKTUSE integer,
  ZSEPCOOKTUSE integer,
  OVEN integer,
  ZOVEN integer,
  OVENFUEL integer,
  ZOVENFUEL integer,
  SEPOVENUSE integer,
  ZSEPOVENUSE integer,
  MICRO integer,
  ZMICRO integer,
  AMTMICRO integer,
  ZAMTMICRO integer,
  OUTGRILL integer,
  ZOUTGRILL integer,
  OUTGRILLFUEL integer,
  ZOUTGRILLFUEL integer,
  NUMMEAL integer,
  ZNUMMEAL integer,
  TOAST integer,
  ZTOAST integer,
  TOASTOVN integer,
  ZTOASTOVN integer,
  COFFEE integer,
  ZCOFFEE integer,
  CROCKPOT integer,
  ZCROCKPOT integer,
  FOODPROC integer,
  ZFOODPROC integer,
  RICECOOK integer,
  ZRICECOOK integer,
  BLENDER integer,
  ZBLENDER integer,
  APPOTHER integer,
  ZAPPOTHER integer,
  DISHWASH integer,
  ZDISHWASH integer,
  DWASHUSE integer,
  ZDWASHUSE integer,
  DWCYCLE integer,
  ZDWCYCLE integer,
  AGEDW integer,
  ZAGEDW integer,
  CWASHER integer,
  ZCWASHER integer,
  TOPFRONT integer,
  ZTOPFRONT integer,
  WASHLOAD integer,
  ZWASHLOAD integer,
  WASHTEMP integer,
  ZWASHTEMP integer,
  RNSETEMP integer,
  ZRNSETEMP integer,
  AGECWASH integer,
  ZAGECWASH integer,
  DRYER integer,
  ZDRYER integer,
  DRYRFUEL integer,
  ZDRYRFUEL integer,
  DRYRUSE integer,
  ZDRYRUSE integer,
  AGECDRYER integer,
  ZAGECDRYER integer,
  TVCOLOR integer,
  ZTVCOLOR integer,
  TVSIZE1 integer,
  ZTVSIZE1 integer,
  TVTYPE1 integer,
  ZTVTYPE1 integer,
  TVONWD1 integer,
  ZTVONWD1 integer,
  TVONWE1 integer,
  ZTVONWE1 integer,
  TVSIZE2 integer,
  ZTVSIZE2 integer,
  TVTYPE2 integer,
  ZTVTYPE2 integer,
  TVONWD2 integer,
  ZTVONWD2 integer,
  TVONWE2 integer,
  ZTVONWE2 integer,
  CABLESAT integer,
  ZCABLESAT integer,
  COMBODVR integer,
  ZCOMBODVR integer,
  SEPDVR integer,
  ZSEPDVR integer,
  PLAYSTA integer,
  ZPLAYSTA integer,
  DVD integer,
  ZDVD integer,
  VCR integer,
  ZVCR integer,
  INTSTREAM integer,
  ZINTSTREAM integer,
  TVAUDIOSYS integer,
  ZTVAUDIOSYS integer,
  DESKTOP integer,
  ZDESKTOP integer,
  NUMLAPTOP integer,
  ZNUMLAPTOP integer,
  NUMTABLET integer,
  ZNUMTABLET integer,
  ELPERIPH integer,
  ZELPERIPH integer,
  NUMSMPHONE integer,
  ZNUMSMPHONE integer,
  CELLPHONE integer,
  ZCELLPHONE integer,
  INTERNET integer,
  ZINTERNET integer,
  INWIRELESS integer,
  ZINWIRELESS integer,
  HEATHOME integer,
  ZHEATHOME integer,
  DNTHEAT integer,
  ZDNTHEAT integer,
  EQUIPM integer,
  ZEQUIPM integer,
  FUELHEAT integer,
  ZFUELHEAT integer,
  EQUIPAGE integer,
  ZEQUIPAGE integer,
  THERMAIN integer,
  ZTHERMAIN integer,
  PROTHERM integer,
  ZPROTHERM integer,
  EQUIPMUSE integer,
  ZEQUIPMUSE integer,
  TEMPHOME integer,
  ZTEMPHOME integer,
  TEMPGONE integer,
  ZTEMPGONE integer,
  TEMPNITE integer,
  ZTEMPNITE integer,
  EQUIPAUX integer,
  ZEQUIPAUX integer,
  EQUIPAUXTYPE integer,
  ZEQUIPAUXTYPE integer,
  FUELAUX integer,
  ZFUELAUX integer,
  BASEHEAT integer,
  ZBASEHEAT integer,
  ATTCHEAT integer,
  ZATTCHEAT integer,
  GARGHEAT integer,
  ZGARGHEAT integer,
  MOISTURE integer,
  ZMOISTURE integer,
  USEMOISTURE integer,
  ZUSEMOISTURE integer,
  AIRCOND integer,
  ZAIRCOND integer,
  COOLTYPE integer,
  ZCOOLTYPE integer,
  CENACHP integer,
  ZCENACHP integer,
  AGECENAC integer,
  ZAGECENAC integer,
  THERMAINAC integer,
  ZTHERMAINAC integer,
  PROTHERMAC integer,
  ZPROTHERMAC integer,
  USECENAC integer,
  ZUSECENAC integer,
  NUMBERAC integer,
  ZNUMBERAC integer,
  WWACAGE integer,
  ZWWACAGE integer,
  USEWWAC integer,
  ZUSEWWAC integer,
  TEMPHOMEAC integer,
  ZTEMPHOMEAC integer,
  TEMPGONEAC integer,
  ZTEMPGONEAC integer,
  TEMPNITEAC integer,
  ZTEMPNITEAC integer,
  BASECOOL integer,
  ZBASECOOL integer,
  ATTCCOOL integer,
  ZATTCCOOL integer,
  GARGCOOL integer,
  ZGARGCOOL integer,
  SWAMPCOL integer,
  ZSWAMPCOL integer,
  NUMCFAN integer,
  ZNUMCFAN integer,
  NUMFLOORFAN integer,
  ZNUMFLOORFAN integer,
  NUMWHOLEFAN integer,
  ZNUMWHOLEFAN integer,
  NUMATTICFAN integer,
  ZNUMATTICFAN integer,
  NOTMOIST integer,
  ZNOTMOIST integer,
  USENOTMOIST integer,
  ZUSENOTMOIST integer,
  FUELH2O integer,
  ZFUELH2O integer,
  H2OHEATAPT integer,
  ZH2OHEATAPT integer,
  WHEATAGE integer,
  ZWHEATAGE integer,
  WHEATSIZ integer,
  ZWHEATSIZ integer,
  MORETHAN1H2O integer,
  ZMORETHAN1H2O integer,
  FUELH2O2 integer,
  ZFUELH2O2 integer,
  LGTINNUM integer,
  ZLGTINNUM integer,
  LGTIN4 integer,
  ZLGTIN4 integer,
  LGTINCAN integer,
  ZLGTINCAN integer,
  LGTINCFL integer,
  ZLGTINCFL integer,
  LGTINLED integer,
  ZLGTINLED integer,
  LGTINCNTL integer,
  ZLGTINCNTL integer,
  LGTOUTNUM integer,
  ZLGTOUTNUM integer,
  LGTOUTCNTL integer,
  ZLGTOUTCNTL integer,
  AUDIT integer,
  AUDITCHG integer,
  EELIGHTS integer,
  FREEAUDIT integer,
  REBATEAPP integer,
  RECYCAPP integer,
  TAXCREDITAPP integer,
  BENOTHER integer,
  ESCWASH integer,
  ESDISHW integer,
  ESDRYER integer,
  ESFREEZE integer,
  ESFRIG integer,
  ESLIGHT integer,
  ESWATER integer,
  ESWIN integer,
  SMARTTHERM integer,
  ELPAY integer,
  ZELPAY integer,
  NGPAY integer,
  ZNGPAY integer,
  LPGPAY integer,
  ZLPGPAY integer,
  FOPAY integer,
  ZFOPAY integer,
  SMARTMETER integer,
  INTDATA integer,
  INTDATAACC integer,
  HHSEX integer,
  ZHHSEX integer,
  HHAGE integer,
  ZHHAGE integer,
  EMPLOYHH integer,
  ZEMPLOYHH integer,
  SDESCENT integer,
  ZSDESCENT integer,
  HOUSEHOLDER_RACE integer,
  ZHOUSEHOLDER_RACE integer,
  EDUCATION integer,
  ZEDUCATION integer,
  NHSLDMEM integer,
  ZNHSLDMEM integer,
  NUMADULT integer,
  ZNUMADULT integer,
  NUMCHILD integer,
  ZNUMCHILD integer,
  ATHOME integer,
  ZATHOME integer,
  MONEYPY integer,
  ZMONEYPY integer,
  USEEL integer,
  ELWARM integer,
  ELCOOL integer,
  ELWATER integer,
  ELFOOD integer,
  ELOTHER integer,
  USENG integer,
  UGWARM integer,
  UGWATER integer,
  UGCOOK integer,
  UGOTH integer,
  USELP integer,
  LPWARM integer,
  LPWATER integer,
  LPCOOK integer,
  LPOTHER integer,
  USEFO integer,
  FOWARM integer,
  FOWATER integer,
  FOOTHER integer,
  USEWOOD integer,
  WDWARM integer,
  WDWATER integer,
  USESOLAR integer,
  SOLWATER integer,
  SOLOTHER integer,
  NWEIGHT double precision,
  BRRWT1 double precision,
  BRRWT2 double precision,
  BRRWT3 double precision,
  BRRWT4 double precision,
  BRRWT5 double precision,
  BRRWT6 double precision,
  BRRWT7 double precision,
  BRRWT8 double precision,
  BRRWT9 double precision,
  BRRWT10 double precision,
  BRRWT11 double precision,
  BRRWT12 double precision,
  BRRWT13 double precision,
  BRRWT14 double precision,
  BRRWT15 double precision,
  BRRWT16 double precision,
  BRRWT17 double precision,
  BRRWT18 double precision,
  BRRWT20 double precision,
  BRRWT21 double precision,
  BRRWT22 double precision,
  BRRWT23 double precision,
  BRRWT24 double precision,
  BRRWT25 double precision,
  BRRWT26 double precision,
  BRRWT27 double precision,
  BRRWT28 double precision,
  BRRWT19 double precision,
  BRRWT29 double precision,
  BRRWT30 double precision,
  BRRWT31 double precision,
  BRRWT32 double precision,
  BRRWT33 double precision,
  BRRWT34 double precision,
  BRRWT35 double precision,
  BRRWT36 double precision,
  BRRWT37 double precision,
  BRRWT38 double precision,
  BRRWT39 double precision,
  BRRWT40 double precision,
  BRRWT41 double precision,
  BRRWT42 double precision,
  BRRWT43 double precision,
  BRRWT44 double precision,
  BRRWT45 double precision,
  BRRWT46 double precision,
  BRRWT47 double precision,
  BRRWT48 double precision,
  BRRWT49 double precision,
  BRRWT50 double precision,
  BRRWT51 double precision,
  BRRWT52 double precision,
  BRRWT53 double precision,
  BRRWT54 double precision,
  BRRWT55 double precision,
  BRRWT56 double precision,
  BRRWT57 double precision,
  BRRWT58 double precision,
  BRRWT59 double precision,
  BRRWT60 double precision,
  BRRWT61 double precision,
  BRRWT62 double precision,
  BRRWT63 double precision,
  BRRWT64 double precision,
  BRRWT65 double precision,
  BRRWT66 double precision,
  BRRWT67 double precision,
  BRRWT68 double precision,
  BRRWT69 double precision,
  BRRWT70 double precision,
  BRRWT71 double precision,
  BRRWT72 double precision,
  BRRWT73 double precision,
  BRRWT74 double precision,
  BRRWT75 double precision,
  BRRWT76 double precision,
  BRRWT77 double precision,
  BRRWT78 double precision,
  BRRWT79 double precision,
  BRRWT80 double precision,
  BRRWT81 double precision,
  BRRWT82 double precision,
  BRRWT83 double precision,
  BRRWT84 double precision,
  BRRWT85 double precision,
  BRRWT86 double precision,
  BRRWT87 double precision,
  BRRWT88 double precision,
  BRRWT89 double precision,
  BRRWT90 double precision,
  BRRWT91 double precision,
  BRRWT92 double precision,
  BRRWT93 double precision,
  BRRWT94 double precision,
  BRRWT95 double precision,
  BRRWT96 text
);

COPY RECS_2015(DOEID,REGIONC,DIVISION,METROMICRO,UATYP10,CDD30YR,CDD65,CLIMATE_REGION_PUB,HDD30YR,HDD65,TYPEHUQ,ZTYPEHUQ,CELLAR,ZCELLAR,BASEFIN,ZBASEFIN,ATTIC,ZATTIC,ATTICFIN,ZATTICFIN,STORIES,ZSTORIES,PRKGPLC1,ZPRKGPLC1,SIZEOFGARAGE,ZSIZEOFGARAGE,KOWNRENT,ZKOWNRENT,YEARMADERANGE,ZYEARMADERANGE,OCCUPYYRANGE,ZOCCUPYYRANGE,STUDIO,ZSTUDIO,BEDROOMS,ZBEDROOMS,NCOMBATH,ZNCOMBATH,NHAFBATH,ZNHAFBATH,OTHROOMS,ZOTHROOMS,TOTROOMS,ZTOTROOMS,WALLTYPE,ZWALLTYPE,ROOFTYPE,ZROOFTYPE,HIGHCEIL,ZHIGHCEIL,DOOR1SUM,ZDOOR1SUM,WINDOWS,ZWINDOWS,TYPEGLASS,ZTYPEGLASS,WINFRAME,ZWINFRAME,ADQINSUL,ZADQINSUL,DRAFTY,ZDRAFTY,UGASHERE,ZUGASHERE,SWIMPOOL,ZSWIMPOOL,MONPOOL,ZMONPOOL,POOL,ZPOOL,FUELPOOL,ZFUELPOOL,RECBATH,ZRECBATH,MONTUB,ZMONTUB,FUELTUB,ZFUELTUB,OUTLET,ZOUTLET,ALTFUELPEV,ZALTFUELPEV,BACKUP,ZBACKUP,SOLAR,NUMFRIG,ZNUMFRIG,SIZRFRI1,ZSIZRFRI1,TYPERFR1,ZTYPERFR1,AGERFRI1,ZAGERFRI1,ICE,ZICE,SIZRFRI2,ZSIZRFRI2,TYPERFR2,ZTYPERFR2,AGERFRI2,ZAGERFRI2,LOCRFRI2,ZLOCRFRI2,NUMFREEZ,ZNUMFREEZ,UPRTFRZR,ZUPRTFRZR,SIZFREEZ,ZSIZFREEZ,AGEFRZR,ZAGEFRZR,STOVEN,ZSTOVEN,STOVENFUEL,ZSTOVENFUEL,DUALCOOKTFUEL,ZDUALCOOKTFUEL,DUALOVENFUEL,ZDUALOVENFUEL,COOKTUSE,ZCOOKTUSE,OVENUSE,ZOVENUSE,STOVE,ZSTOVE,STOVEFUEL,ZSTOVEFUEL,SEPCOOKTUSE,ZSEPCOOKTUSE,OVEN,ZOVEN,OVENFUEL,ZOVENFUEL,SEPOVENUSE,ZSEPOVENUSE,MICRO,ZMICRO,AMTMICRO,ZAMTMICRO,OUTGRILL,ZOUTGRILL,OUTGRILLFUEL,ZOUTGRILLFUEL,NUMMEAL,ZNUMMEAL,TOAST,ZTOAST,TOASTOVN,ZTOASTOVN,COFFEE,ZCOFFEE,CROCKPOT,ZCROCKPOT,FOODPROC,ZFOODPROC,RICECOOK,ZRICECOOK,BLENDER,ZBLENDER,APPOTHER,ZAPPOTHER,DISHWASH,ZDISHWASH,DWASHUSE,ZDWASHUSE,DWCYCLE,ZDWCYCLE,AGEDW,ZAGEDW,CWASHER,ZCWASHER,TOPFRONT,ZTOPFRONT,WASHLOAD,ZWASHLOAD,WASHTEMP,ZWASHTEMP,RNSETEMP,ZRNSETEMP,AGECWASH,ZAGECWASH,DRYER,ZDRYER,DRYRFUEL,ZDRYRFUEL,DRYRUSE,ZDRYRUSE,AGECDRYER,ZAGECDRYER,TVCOLOR,ZTVCOLOR,TVSIZE1,ZTVSIZE1,TVTYPE1,ZTVTYPE1,TVONWD1,ZTVONWD1,TVONWE1,ZTVONWE1,TVSIZE2,ZTVSIZE2,TVTYPE2,ZTVTYPE2,TVONWD2,ZTVONWD2,TVONWE2,ZTVONWE2,CABLESAT,ZCABLESAT,COMBODVR,ZCOMBODVR,SEPDVR,ZSEPDVR,PLAYSTA,ZPLAYSTA,DVD,ZDVD,VCR,ZVCR,INTSTREAM,ZINTSTREAM,TVAUDIOSYS,ZTVAUDIOSYS,DESKTOP,ZDESKTOP,NUMLAPTOP,ZNUMLAPTOP,NUMTABLET,ZNUMTABLET,ELPERIPH,ZELPERIPH,NUMSMPHONE,ZNUMSMPHONE,CELLPHONE,ZCELLPHONE,INTERNET,ZINTERNET,INWIRELESS,ZINWIRELESS,HEATHOME,ZHEATHOME,DNTHEAT,ZDNTHEAT,EQUIPM,ZEQUIPM,FUELHEAT,ZFUELHEAT,EQUIPAGE,ZEQUIPAGE,THERMAIN,ZTHERMAIN,PROTHERM,ZPROTHERM,EQUIPMUSE,ZEQUIPMUSE,TEMPHOME,ZTEMPHOME,TEMPGONE,ZTEMPGONE,TEMPNITE,ZTEMPNITE,EQUIPAUX,ZEQUIPAUX,EQUIPAUXTYPE,ZEQUIPAUXTYPE,FUELAUX,ZFUELAUX,BASEHEAT,ZBASEHEAT,ATTCHEAT,ZATTCHEAT,GARGHEAT,ZGARGHEAT,MOISTURE,ZMOISTURE,USEMOISTURE,ZUSEMOISTURE,AIRCOND,ZAIRCOND,COOLTYPE,ZCOOLTYPE,CENACHP,ZCENACHP,AGECENAC,ZAGECENAC,THERMAINAC,ZTHERMAINAC,PROTHERMAC,ZPROTHERMAC,USECENAC,ZUSECENAC,NUMBERAC,ZNUMBERAC,WWACAGE,ZWWACAGE,USEWWAC,ZUSEWWAC,TEMPHOMEAC,ZTEMPHOMEAC,TEMPGONEAC,ZTEMPGONEAC,TEMPNITEAC,ZTEMPNITEAC,BASECOOL,ZBASECOOL,ATTCCOOL,ZATTCCOOL,GARGCOOL,ZGARGCOOL,SWAMPCOL,ZSWAMPCOL,NUMCFAN,ZNUMCFAN,NUMFLOORFAN,ZNUMFLOORFAN,NUMWHOLEFAN,ZNUMWHOLEFAN,NUMATTICFAN,ZNUMATTICFAN,NOTMOIST,ZNOTMOIST,USENOTMOIST,ZUSENOTMOIST,FUELH2O,ZFUELH2O,H2OHEATAPT,ZH2OHEATAPT,WHEATAGE,ZWHEATAGE,WHEATSIZ,ZWHEATSIZ,MORETHAN1H2O,ZMORETHAN1H2O,FUELH2O2,ZFUELH2O2,LGTINNUM,ZLGTINNUM,LGTIN4,ZLGTIN4,LGTINCAN,ZLGTINCAN,LGTINCFL,ZLGTINCFL,LGTINLED,ZLGTINLED,LGTINCNTL,ZLGTINCNTL,LGTOUTNUM,ZLGTOUTNUM,LGTOUTCNTL,ZLGTOUTCNTL,AUDIT,AUDITCHG,EELIGHTS,FREEAUDIT,REBATEAPP,RECYCAPP,TAXCREDITAPP,BENOTHER,ESCWASH,ESDISHW,ESDRYER,ESFREEZE,ESFRIG,ESLIGHT,ESWATER,ESWIN,SMARTTHERM,ELPAY,ZELPAY,NGPAY,ZNGPAY,LPGPAY,ZLPGPAY,FOPAY,ZFOPAY,SMARTMETER,INTDATA,INTDATAACC,HHSEX,ZHHSEX,HHAGE,ZHHAGE,EMPLOYHH,ZEMPLOYHH,SDESCENT,ZSDESCENT,HOUSEHOLDER_RACE,ZHOUSEHOLDER_RACE,EDUCATION,ZEDUCATION,NHSLDMEM,ZNHSLDMEM,NUMADULT,ZNUMADULT,NUMCHILD,ZNUMCHILD,ATHOME,ZATHOME,MONEYPY,ZMONEYPY,USEEL,ELWARM,ELCOOL,ELWATER,ELFOOD,ELOTHER,USENG,UGWARM,UGWATER,UGCOOK,UGOTH,USELP,LPWARM,LPWATER,LPCOOK,LPOTHER,USEFO,FOWARM,FOWATER,FOOTHER,USEWOOD,WDWARM,WDWATER,USESOLAR,SOLWATER,SOLOTHER,NWEIGHT,BRRWT1,BRRWT2,BRRWT3,BRRWT4,BRRWT5,BRRWT6,BRRWT7,BRRWT8,BRRWT9,BRRWT10,BRRWT11,BRRWT12,BRRWT13,BRRWT14,BRRWT15,BRRWT16,BRRWT17,BRRWT18,BRRWT20,BRRWT21,BRRWT22,BRRWT23,BRRWT24,BRRWT25,BRRWT26,BRRWT27,BRRWT28,BRRWT19,BRRWT29,BRRWT30,BRRWT31,BRRWT32,BRRWT33,BRRWT34,BRRWT35,BRRWT36,BRRWT37,BRRWT38,BRRWT39,BRRWT40,BRRWT41,BRRWT42,BRRWT43,BRRWT44,BRRWT45,BRRWT46,BRRWT47,BRRWT48,BRRWT49,BRRWT50,BRRWT51,BRRWT52,BRRWT53,BRRWT54,BRRWT55,BRRWT56,BRRWT57,BRRWT58,BRRWT59,BRRWT60,BRRWT61,BRRWT62,BRRWT63,BRRWT64,BRRWT65,BRRWT66,BRRWT67,BRRWT68,BRRWT69,BRRWT70,BRRWT71,BRRWT72,BRRWT73,BRRWT74,BRRWT75,BRRWT76,BRRWT77,BRRWT78,BRRWT79,BRRWT80,BRRWT81,BRRWT82,BRRWT83,BRRWT84,BRRWT85,BRRWT86,BRRWT87,BRRWT88,BRRWT89,BRRWT90,BRRWT91,BRRWT92,BRRWT93,BRRWT94,BRRWT95,BRRWT96)
FROM 'D:/Programming/Projects/2015 EIA RECS/RECS2015.csv' DELIMITER ',' CSV HEADER;

-- SQL Query Exercises for 2015 EIA RECS Data

/* Q1 Find the percent of households from the Pacific division (division = 10) that made changes as a result of a free home energy audit
 among all Pacific division households that made changes as a result of any home energy audit. */
SELECT (COUNT (freeaudit):decimal / COUNT (allaudit))*100 as PercentFreeChange
FROM
      (SELECT COUNT (auditchg)
       FROM RECS_2015
       WHERE
       auditchg = 1 AND
       freeaudit = 1 AND
       division = 10) AS freeaudit,
      (SELECT count (auditchg)
       FROM RECS_2015
       WHERE
       auditchg = 1 AND
       division = 10) AS allaudit;
-- Q1 Answer: 20.49%

/* Q2 For each housing type, find the number of households that received an energy audit. Order by highest number of households type. */
SELECT typehuq,
             COUNT(typehuq) AS typehuq_hum
    FROM     RECS_2015
    WHERE    audit = 1
    GROUP BY typehuq
    ORDER BY typehuq_num DESC;
/* Q2 Answer: Household Type | Number of Households
                           2 , 363
                           3 , 37
                           5 , 26
                           1 , 17
                           4 , 15                 */

/* Q3 Find the housing type, cooling degree days, heating degree days, division, year made, and climate
      for all households with a non-heated swimming pool and no hot tub. */
SELECT typehuq, cdd65, hdd65, division, yearmaderange, climate_region_pub
FROM RECS_2015
WHERE swimpool = 1 AND
       pool = 1 AND
       recbath = 0;
-- Q3 Answer: Table

/* Q4 Find the spread of heating degree days and the spread of cooling degree days, for all households
      which received an energy audit, grouped by division. Do not include househoulds from the New England
      or Middle Atlantic divisions. Order by ascending division code. */
SELECT division, (MAX(HDD65) - MIN(HDD65)) AS HDD65_Spread, (MAX(CDD65) - MIN(CDD65)) AS CDD65_Spread
FROM RECS_2015
WHERE division <> 1 AND
      division <> 2 AND
      audit = 1
GROUP BY division
ORDER BY division asc;
-- Q4 Answer: Table
       
/* Q5 Find all divisions with a higher average HDD65 than the average HDD65 of the Pacific division. Return the divisions and average HDD65 */
SELECT typehuq, cdd65, hdd65, division, yearmaderange, climate_region_pub
FROM RECS_2015
WHERE swimpool = 1 AND
       pool = 1 AND
       recbath = 0;
/* Q5 Answer: Household Type | Number of Households
                           6 , 2668
                           8 , 5335
                           2 , 5412
                           1 , 6566
                           3 , 5832
                           4 , 5876
                                            */
